apiVersion: apps/v1
kind: Deployment
metadata:
  name: tbcommerce
  labels:
    app: tbcommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tbcommerce
  template:
    metadata:
      labels:
        app: tbcommerce
    spec:
      containers:
        - name: tbcommerce
          image: 176295807911.dkr.ecr.us-east-1.amazonaws.com/tbcommerce
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
